### ISSUE TITLE
missing required settings

### ISSUE THREAD

**Issue by Luckyxgaiss** [willasm/vc-weather#8] opened 2024-10-10 12:57 UTC
Hello! thank you so much for the new plugin.

But I have some problems installing the new plugin whether through BRAT or manually.
# Through BRAT
It can be registered by BRAT, but just after the BRAT's message says that the new plugin has been registered successfully, there's another message says "Visual Crossing Weather plugin is missing required settings. Please configure the plugins settings."
![vc-weather](https://github.com/user-attachments/assets/62dd4c1b-12a7-4ec8-a90e-9d92a9194f06)

I just do the steps as you said: 
1. copy the link
2. use the command "Add a plugin for testing", and paste the link
3. click "Add Plugin"
then there are two message boxes that I mentioned above

# Manual
I download the two files in the latest release 0.2.1, but that doesn't work.

Actually, I'm not able to see what's in the plugin setting page, because there's nothing.
I wonder if there are some conflicts with other plugins or I just missed some necessary steps.
I appreciate your upcoming reply!

**Comment by willasm** [comment] 2024-10-10 18:29
You need to go into the plugins settings and add your API key and set your primary location. Also you will need to add an exclude folder as well (will use your template folder if it is detected). Until these are filled in the plugin can not work. The warning message at first startup is shown to everyone when first installed as the plugin needs that information in order to function.

You say you can not see the settings? That should never happen? What OS are you using and which version of Obsidian? It has been tested under Windows and Linux but not Mac. It currently is not supported for mobile yet but even if you managed to install it on mobile you should still be able to see the settings page. The only way you would not see the settings page is if it did not fully install. Try looking in the plugins settings folder and verify that the files `main.js` and `manifest.json` are there. You can find this folder in `(path to your vault)/.obsidian/plugins/visual-crossing-weather`. The `.obsidian` sub-folder is a hidden folder so you will need to turn on 'show hidden folders' in your file manager. The fact that you are getting the missing settings warning tells me that at least the `main.js` file installed correctly but it may not have installed the `manifest.json` file. Both are required.

Let me know what you see in that folder, William.

**Comment by willasm** [comment] 2024-10-10 20:33
Just uploaded a new version 0.2.2

Update is not related to your issue (still not sure what is happening there), but see if Brat actually updates it successfully or not.

Thanks, William.

**Comment by Luckyxgaiss** [comment] 2024-10-11 03:14
Thanks for your reply!
I use Win11 23H2，and the obsidian version is v1.6.7.
After I install vc-weather through BRAT I can find the two files `main.js` and `manifest.json` under the folder `(path to the vault)/.obsidian/plugins/visual-crossing-weather`. 

I tried to install vc-weather in a virtual machine using Win10 22H2(which has not installed obsidian before)，but the settings page is still blank. And I asked my friend(Win11 23H2, v1.6.7) to try it, and he got the same result.

**Comment by willasm** [comment] 2024-10-11 05:44
I just tested it on Windows 10 (I use Linux) and it works fine for me. From the settings menu does the plugin appear in the list of plugins when you select `Community plugins` on the left (at the bottom of options section)? Does the plugin name appear at all in the list on the left under the `Community plugins` section?

Can you do me a favor and test it on a new empty vault? Brat is not required for this method and it will eliminate any possible conflicts with other plugins.

Create an empty folder anywhere you like and in Obsidian click on the vault name in the bottom left, then select `manage vaults` from the menu, then from the popup window select the second option `Open folder as vault` and select the empty folder you just created. Now exit Obsidian and run your file manager and copy the folder `visual-crossing-weather` from the vault you currently have the plugin installed to and paste it into `(path to the new empty vault)/.obsidian/plugins`. You will likely have to create the folders `.obsidian` and the sub-folder in .obsidian `plugins` first as they probably will not exist.

Now open Obsidian again with the new empty vault selected and enable the plugin in Obsidians settings. If you can access the plugins settings now then the issue is caused by something else and I can help you track it down.

Please let me know if this works for you. Thanks, William.

**Comment by willasm** [comment] 2024-10-11 06:21
It just occured to me that you can just create the `data.json` file yourself. In notepad paste in the following and put in your API key where it says to and change the location_one key, `Edmonton` to the name of your city. If you created the empty vault as suggested above you will also need to create a folder inside the vault named `Templates` or change the key `excludeFolder` from "Templates" to your Templates folder in your original vault. After doing this restart Obsidian and see if the plugin loaded or not. If successful you should see the the weather information in the statusbar.

```json
{
  "apikey": "YOUR API KEY HERE",
  "location_one": "Edmonton",
  "location_two": "",
  "location_three": "",
  "location_four": "",
  "location_five": "",
  "units": "metric",
  "excludeFolder": "Templates",
  "excludeFolder2": "",
  "updateFrequency": "15",
  "statusbarActive": true,
  "statusbarCycle": true,
  "weatherTemplate1SB": "🔸%address%: %dow2-now% %month3-now% %date1-now%🔸High: %tempmax-today%° Low: %tempmin-today%°🔸Currently: %conditions% Temp: %temp%° Feels Like: %feelslike%°🔸",
  "weatherTemplate2SB": "🔸%address%: %dow2-in1day% %month3-in1day% %date1-in1day%🔸High: %tempmax-in1day%° Low: %tempmin-in1day%°🔸Clouds: %cloudcover-in1day% Probabilty of precipitation: %precipprob-in1day% (%preciptype-in1day%)🔸",
  "weatherTemplate1": "Short one liner\n%conditions% • Current Temp: %temp%° • Feels Like: %feelslike%°\n",
  "weatherTemplate2": "More detailed\n%address%: %dow2-now% %month4-now% %date1-now% - %hours12-now%:%mins-now% %ampm2-now%\nProbability of precipitation: %precipprob% • (%preciptype%)\nCurrent Temp: %temp%°C • Feels Like: %feelslike%°C\nWind: %windspeed-today% km/h from the %winddirstr-today% with gusts up to %windgust-today% km/h\nSunrise: %sunrise-today% • Sunset: %sunset-today%\n",
  "weatherTemplate3": "Historical DIV\n<img src=%iconurl% />&nbsp;%month4-now% %date1-now% %year1-now% • %hours12-now%:%mins-now% %ampm2-now% • %conditions%\n&nbsp;Recorded Temp: %temp% • Felt like: %feelslike%\n&nbsp;Wind: %windspeed-today% km/h from the %winddirstr-today% with gusts up to %windgust-today% km/h\n&nbsp;Sunrise: %sunrise-today% • Sunset: %sunset-today%",
  "weatherTemplate4": "Current DIV\n<img src=%iconurl%  />&nbsp;%month4-now% %date1-now% %year1-now% • %hours12-now%:%mins-now% %ampm2-now% • %conditions%\n&nbsp;Current Temp: %temp% • Feels like: %feelslike%\n&nbsp;Wind: %windspeed-today% km/h from the %winddirstr-today% with gusts up to %windgust-today% km/h\n&nbsp;Sunrise: %sunrise-today% • Sunset: %sunset-today%",
  "weatherTemplate5": "Current DIV Text\n%month4-now% %date1-now% %year1-now% • %hours12-now%:%mins-now% %ampm2-now% • %conditions%\nCurrent Temp: %temp% • Feels like: %feelslike%\nWind: %windspeed-today% km/h from the %winddirstr-today% with gusts up to %windgust-today% km/h\nSunrise: %sunrise-today% • Sunset: %sunset-today%",
  "weatherTemplate6": "",
  "weatherTemplate7": "",
  "weatherTemplate8": "Today with next 3 days in a table\n|         |  Today<br>%month3-today% %date1-today%   |  %dow1-in1day%<br>%month3-in1day% %date1-in1day%  |  %dow1-in2days%<br>%month3-in2days% %date1-in2days%  |  %dow1-in3days%<br>%month3-in3days% %date1-in3days%  |\n| ------- | :---------------: | :---------------: | :---------------: | :---------------: |\n| High    | **%tempmax-today%°C**          | **%tempmax-in1day%°C**          | **%tempmax-in2days%°C**          | **%tempmax-in3days%°C**          |\n| Low     | **%tempmin-today%°C**          | **%tempmin-in1day%°C**          | **%tempmin-in2days%°C**          | **%tempmin-in3days%°C**          |\n| Skies   | %conditions-today%             | %conditions-in1day% | %conditions-in2days%           | %conditions-in3days%           |\n| PoP     | %precipprob-today%                | %precipprob-in1day%               | %precipprob-in2days%               | %precipprob-in2days%               |\n"
}
```

**Comment by Luckyxgaiss** [comment] 2024-10-11 15:20
# community plugin
The plugin can be seen in the settings menu (I do this in a new vault):
![vc-weather空白页](https://github.com/user-attachments/assets/725e0f1f-601c-4dc1-aca6-32e6063f53f7)
![vc-weather条目](https://github.com/user-attachments/assets/0ac65fb1-32c1-49b1-b358-c171e3d61577)

# new vault
I created a new vault, and created a folder named `plugins` under `./obsidian`, then I copied the folder `visual-crossing-weather` into the new vault's `plugins` folder from the former vault, but the page is still blank as the picture pasted above.

# create data.json myself
I created the file `data.json` and fill in my api-key and the city name, then it work! Now I can see the weather information in the statusbar :
![vc-ewather状态栏](https://github.com/user-attachments/assets/00be1124-9a98-4f75-9890-c957f1211aab)
and "select template to insert" function also works perfectly.

So it seems that the only problem is that the settings page cannot come out.🤔

**Comment by willasm** [comment] 2024-10-11 17:32
I was finally able to reproduce this. On the left under `Core plugins` in the `Templates` core plugin, if a Template folder, or Date format, or Time format is not defined then the settings page is blank. When any of those settings are defined, Obsidian creates a file `templates.json` in the `.obsidian` folder. My plugin uses this file to get the users template folder to auto fill the excludeFolder key in the plugins settings. You can expect a fix for this very soon.

In the meantime open the settings for the Core plugin `Templates` and define any setting. This will generate the `Templates.json` file in the `.obsidian` folder. In the screenshot I set the folder to `Templates`. The folder does not actually have to exist in the vault, it is just there to create the settings template.json file.

Core plugins - Templates screenshot...

![CoreTemplates](https://github.com/user-attachments/assets/1c308803-3b13-4bfe-a7fb-2279472770a4)

**Comment by willasm** [comment] 2024-10-11 23:00
You can ignore the work around in my previous post. This should be fixed in v0.2.3 which I just uploaded. Thanks for bringing this to my attention. Never would have found this otherwise. Let me know if the issue is fixed for you.

Thanks, William.

**Comment by Luckyxgaiss** [comment] 2024-10-12 03:12
Thanks for fixing the problem! Now the settings page is shown fully, and all functions work perfectly!
And thank you for bringing the great plugin! Good luck with your job🌹

**Comment by willasm** [comment] 2024-10-12 18:35
Thanks for the feedback. If you have any other issues, just let me know

**Closed by willasm** 2024-10-12 18:35 UTC
